@export var expShards = 0
@export var rewardPoints = 0
@export var rank = 0
@export var maxRank = 0
@export var dayOfMonth = 999
@export var collectedExpShards = 0
@export var rewardsPointsAdded = 0 #For each 50 shards
@export var listOfResources :Array[Resource] = []
@export var listOfDailyBalance = [0,0,0,0,0,0,0]
@export var negativeNumber = 0
@export var positiveNumber = 0
@export var daysPassed = 0
